const response_list = [];

response_list["GuideCake"] = [ { 'slot': '맛있는|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '미식가인 당신에게 가장 잘 어울리는 맛있는 케이크 알려드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_01' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_01' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '방울방울 생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_01.png' }, 'referenceText': { 'type': 'string', 'value': '바로 촉촉한 생크림과 달콤한 과일이 어우러진 방울방울 생크림 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M11' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_01.png' }, 'referenceText': { 'type': 'string', 'value': '부드러운 생크림이 입안에서 살살 녹아 싫어하는 고객님을 찾을 수 없으니 걱정 말고 구매하세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '선물|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '선물용이라면 누구나 좋아하시는 케이크가 딱이에요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_02' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_02' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '마이넘버원2' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_02.png' }, 'referenceText': { 'type': 'string', 'value': '바로 남녀노소 관계없이 누구나 즐기는 마이넘버원2 케이크가 있답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '블루베리요거트, 딸기요거트, 치즈, 초코, 모카, 고구마 6가지 맛을 한 번에 즐길 수는 멋진 선물이 될 거에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '고구마|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '고구마에 달콤한 맛을 좋아하시는군요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_03' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_03' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '고구마가 반한 티라미수' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_03.png' }, 'referenceText': { 'type': 'string', 'value': '온 가족이 함께 먹을 수 있는 고구마가 반한 티라미수가 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_03.png' }, 'referenceText': { 'type': 'string', 'value': '진한 티라미수케이크와 달콤한 밤고구마케이크, 두 가지 맛을 한 번에 맛보세요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '작은|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '작지만 정말 맛있는 케이크가 준비되어 있답니다.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_04' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_04' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '올망졸망 쁘띠생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_04.png' }, 'referenceText': { 'type': 'string', 'value': '바로 이름도 귀여운 올망졸망쁘띠생크림 케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 과일이 어우러진 고소한 생크림 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '타요|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '우리 꼬마 손님이 드실 케이크가 필요하시군요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_05' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_05' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '꼬마버스 타요' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_05.png' }, 'referenceText': { 'type': 'string', 'value': '우리 아이들이 좋아하는 귀여운 친구 꼬마버스 타요가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_05.png' }, 'referenceText': { 'type': 'string', 'value': '학교에간 타요 이야기로 만든 어린이 생일파티용 대형축하 초코케이크에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '모카|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '깊고 진한 모카 케이크를 좋아하시군요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_06' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_06' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '내가찾던 카페모카 가족' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_06.png' }, 'referenceText': { 'type': 'string', 'value': '커피향 가득한 케이크로 내가 찾던 카페모카 가족이 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '하트마카롱과 에펠탑 초콜릿으로 장식해서 보기 좋을뿐만 아니라 맛도 최고랍니다' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '캐릭터|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '모든 아이들이 좋아하는 캐릭터 케이크가 여기 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_07' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_07' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '노래하는 뽀로로와 친구들' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_07.png' }, 'referenceText': { 'type': 'string', 'value': '노래하는 뽀로로와 친구들은 생일축하용 케이크로 딱이에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아이들이 좋아하는 뽀로로 스티커와 배경지가 들어 있어 꼬마 손님들이 아주 좋아할거에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '상어|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아이들이 좋아하는 케이크를 찾으세요? ' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_08' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_08' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '노래하는 핑크퐁과 상어가족의 피크닉' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_08.png' }, 'referenceText': { 'type': 'string', 'value': '최고의 인기캐릭터로 노래하는 핑크퐁과 상어가족의 피크닉이 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_08.png' }, 'referenceText': { 'type': 'string', 'value': '아기상어를 누르면 상어가족 노래가 나오는 뮤직 케이크랍니다' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '아이들|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아이들이 좋아하는 케이크를 찾으세요? ' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_09' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_09' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '노래하는 핑크퐁과 상어가족의 피크닉' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_09.png' }, 'referenceText': { 'type': 'string', 'value': '최고의 인기캐릭터로 노래하는 핑크퐁과 상어가족의 피크닉이 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아기상어를 누르면 상어가족 노래가 나오는 뮤직 케이크랍니다' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '비싼|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '럭셔리한 당신에게 가장 잘 어울리는 케이크가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_10' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '티라미수 크레이프' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_10.png' }, 'referenceText': { 'type': 'string', 'value': '한겹 한겹 촉촉함을 느낄 수 있는 티라미수 크레이프가 딱이랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 크레이프 사이로 진한 티라미수의 참맛을 느낄 수 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '여러가지|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '여러가지 맛을 즐길수 있는 케이크를 찾으세요? ' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_11' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_11' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '마이넘버원2' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_11.png' }, 'referenceText': { 'type': 'string', 'value': '바로 남녀노소 관계없이 누구나 즐기는 마이넘버원2 케이크가 있답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '블루베리요거트, 딸기요거트, 치즈, 초코, 모카, 고구마 6가지 맛을 한 번에 즐길 수 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '가족|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '입맛이 각각 다른 우리가족이라도 모두가 좋아하는 케이크를 알려드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_12' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_12' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '사각사각 상콤바구니' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_12.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일의 궁합이 일품인 사각사각 상콤바구니 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '생과일이 듬뿍 들어있고,  부드러운 생크림이 녹아 내리는 파리바게뜨 인기 생크림 케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '생크림|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 생크림을 좋아하는 당신의 마음도 부드러울 꺼 같아요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_13' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_13' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '방울방울 생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_13.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일이 어우러진 방울방울 생크림 케이크을 추천해요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 생크림이 입안에서 살살 녹는, 파리바게뜨 넘버원 생크림 케이크입니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '이만원|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '2만원대 최고의 케이크를 알려드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_14' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_14' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '방울방울 생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_14.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일이 어우러진 방울방울 생크림 케이크을 추천해요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 생크림이 입안에서 살살 녹는, 파리바게뜨 넘버원 생크림 케이크입니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '저렴한|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '저렴하면서도 정말 맛있는 케이크를 추천드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_15' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_15' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '치즈가 부드러운 시간' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_15.png' }, 'referenceText': { 'type': 'string', 'value': '치즈가 부드러운 시간 한 번 드셔보세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '크림치즈와 계란을 1,000번 이상 저어 만들어 부드럽고 진한 치즈 맛이 최고랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '깔끔한|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '깔끔한 당신에게 어울리는 케이크를 알려드릴게요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_16' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_16' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '방울방울 생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_16.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일이 어우러진 방울방울 생크림이 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 생크림이 입안에서 살살 녹는, 파리바게뜨 넘버원 생크림 케이크입니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '상큼한|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '상큼한 당신에게 딱 맞는 케이크가 있네요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_17' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_17' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '프리미엄베리생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_17.png' }, 'referenceText': { 'type': 'string', 'value': '프리미엄베리생크림 케이크 어떠세요?' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_17.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 베리가 어우러져 정말 상큼한 맛을 느끼실 수 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M10' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '가성비|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '가성비 최고의 케이크를 알려드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_18' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_18' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '초코반 딸기반 케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_18.png' }, 'referenceText': { 'type': 'string', 'value': '한 번에 두가지 맛을 즐길 수 있는 초코반 딸기반 케이크가 있어요. ' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '초코와 딸기 생크림을 동시에 즐길 수 있는 달콤 상큼한 케이크랍니다' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '사진|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아무렇게나 찍어도 멋진 연출이 가능한 케이크를 추천드려요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_19' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_19' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '방울방울 생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_19.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일이 어우러진 방울방울 생크림 케이크가 있어요. ' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '생크림이 입안에서 살살 녹는 부드럽고 환상적인 맛을 느낄수 있을 뿐만 아니라 아름다운 사진까지 얻으실 수 있답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '과일|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '환상적인 맛의 과일케이크를 알려드릴께요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_20' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_20' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '프리미엄베리생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_20.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 베리가 어우러진 프리미엄베리생크림 케이크가 그 주인공이랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉하고 상큼한 케이크로 환상적인 맛을 느낄수 있을 뿐만 아니라 아름다운 사진까지 얻으실 수 있답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '부드러운|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 당신에게 어울리는 케이크가 있네요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_21' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_21' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '치즈케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_21.png' }, 'referenceText': { 'type': 'string', 'value': '입안에서 사르르녹는 치즈케이크 어떠세요?' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '크림치즈의 부드럽고 촉촉한 맛이 일품으로 오랜 기간 사랑 받아온 최고의 치즈케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '부모님|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부모님께 드릴 케이크를 찾으시다니 효자 효녀이시네요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_22' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_22' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '티라미수 오리지날레' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_22.png' }, 'referenceText': { 'type': 'string', 'value': '이탈리아 베네치아에 본연의 맛을 그대로 간직한 티라미수 오리지날레라면 부모님이 좋아하실거에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 모카스폰지와 부드러운 마스카포네치즈가 어우러져 있는 깊고 진한 맛의 티라미수 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '뽀로로|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '뽀로로만큼 모든 아이들이 좋아하는 캐릭터도 없지요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_23' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_23' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '뽀로로와 함께 캠핑가요' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_23.png' }, 'referenceText': { 'type': 'string', 'value': '뽀로로와 크롱의 즐거운 캠핑 이야기가 담긴 뽀로로와 즐거운 캠핑가요가 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아이들과 함께하는 파티에서 즐거운 캠핑계획도 만들어보세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '달콤한|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '달콤한 성격의 당신에게 달달한 추천해볼게요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_24' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_24' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '사각사각 상콤바구니' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_24.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일의 궁합이 일품인 사각사각 상콤바구니 케이크가 어떨까요?' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '생과일이 듬뿍 들어있고,  부드러운 생크림이 녹아 내리는 파리바게뜨 인기 생크림 케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '3만원|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '3만원대 최고의 케이크를 알려드릴게요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_25' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_25' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '사각사각 상콤바구니' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_25.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일의 궁합이 일품인 사각사각 상콤바구니 케이크가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '생과일이 듬뿍 들어있고,  부드러운 생크림이 녹아 내리는 파리바게뜨 인기 생크림 케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '2단|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '흔치 않은 2단 케이크를 찾으시는군요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_26' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_26' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '사파리 친구들' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_26.png' }, 'referenceText': { 'type': 'string', 'value': '귀여운 동물들을 만날 수 있는 사파리 친구들을 추천드려요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '층별로 초코맛, 아몬드맛으로 아이부터 어른까지 모두를 만족시키는 콤비네이션 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '예쁜|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '예쁜 당신에게 딱 어울리는 케이크가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_27' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_27' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '생딸기치즈케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_27.png' }, 'referenceText': { 'type': 'string', 'value': '프리미엄 급의 부드럽고 맛있는 생딸기치즈케이크를 즐겨보세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '속에는 상큼한 딸기 젤리가 들어있고, 층층이 딸기와 치즈크림이 어울려져 있어 맛이 끝내준답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '달지 않은|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '너무 달지 않은 케이크를 원하시나봐요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_28' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_28' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '티라미수 오리지날레' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_28.png' }, 'referenceText': { 'type': 'string', 'value': '이탈리아 베네치아에 본연의 맛을 그대로 간직한 티라미수 오리지날레가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 모카스폰지와 부드러운 마스카포네치즈가 어우러져 있는 깊고 진한 맛의 티라미수 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '아내|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '어머, 아내분 생일이세요? 축하드려요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_29' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_29' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '올망졸망 쁘띠생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_29.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 과일이 어우러진 고소한 생크림 케이크 올망졸망 쁘띠생크림을 추천드려요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아내분께서 너무 좋아서 꼬옥 안아주실거에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '남편|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '어머, 남편분 생일이세요? 축하드려요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_30' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_30' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '올망졸망 쁘띠생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_30.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 과일이 어우러진 고소한 생크림 케이크 올망졸망 쁘띠생크림을 추천드려요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '남편분께서 케이크 뿐만 아니라 고객님께도 흠뻑 빠질거에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '진한|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '제대로 된 깊고 진한 맛을 느끼고 싶으시군요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_31' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_31' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '진한듀얼치즈케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_31.png' }, 'referenceText': { 'type': 'string', 'value': '그렇다면 2가지 리얼치즈로 깊고 진한 치즈의 맛을 느낄 수 있는 진한듀얼치즈케이크를 드셔보세요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '진한 맛을 원하시는 고객님에게 딱 맞는 프리미엄 치즈케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '우유|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '신선한 우유의 맛을 느껴보실래요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_32' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_32' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '순수秀우유케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_32.png' }, 'referenceText': { 'type': 'string', 'value': '유기농 목장의 깨끗한 우유가 그대로 들어간 순수우유케이크를 추천드려요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '청정지역인 강원도 해발 천 미터 높이에 있는 유기농목장의 고소하고 깨끗한 우유 본연의 맛을 느껴보세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '콩순이|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '꼬마 손님이 콩순이를 좋아하나봐요~' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_37' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_37' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '엉뚱발랄 콩순이 케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_37.png' }, 'referenceText': { 'type': 'string', 'value': '화사한 핑크빛의 엉뚱발랄 콩순이 케이크가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '우리의 콩순이 파티셰와 함께 행복한 파티하세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '초코|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '초코 케이크하면 달콤한 이 케이크를 빼놓을 수 없지요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_38' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_38' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '초코우유푸딩케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_38.png' }, 'referenceText': { 'type': 'string', 'value': '바로 초코우유푸딩케이크에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 초코우유 푸딩 속 바삭한 초코크런치가 들어있는 뛰어난 식감의 떠먹는 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '커플|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '사랑스러운 커플이 예쁘게 먹을 수 있는 올망졸망쁘띠생크림 케이크를 추천드려요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_42' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_42' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '올망졸망 쁘띠생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_42.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 과일이 어우러진 고소한 생크림 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '올망졸망 쁘띠생크림 케이크와 함께 행복한 사랑하세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '또봇|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '여기 또봇 델타트론과 어트벤처Y가 있네요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_43' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_43' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '출동! 또봇탐험대' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_43.png' }, 'referenceText': { 'type': 'string', 'value': '도시를 지키는 위풍당당한 모습에 출동! 또봇탐험대를 만나보아요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '우리의 영웅 또봇과 함께 즐거운 생일파티 되세요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '치즈|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드럽고 촉촉한 치즈 맛을 좋아하시나봐요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_44' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_44' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '치즈 케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_44.png' }, 'referenceText': { 'type': 'string', 'value': '치즈 케이크 하면 두말할 나위 없이 파리바게뜨의 치즈케이크가 최고죠' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '크림치즈의 부드럽고 촉촉한 맛이 일품으로 오랜 기간 사랑 받아온 최고의 치즈케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '어벤저스|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '어벤져스 케이크 있는거 어떻게 아셨어요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_45' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_45' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '캡틴아메리카:시빌워 케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_45.png' }, 'referenceText': { 'type': 'string', 'value': '캡틴아메라키 시빌워 케이크가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '어벤져스 히어로인 아이언맨과 캡틴아메리카 피규어가 멋지게 들어가 있어 먹고 난 후에는 소장도 가능해요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '심플한|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '심플한 케이크를 찾으세요? ' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_46' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_46' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '큐티 화이트' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_46.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일의 궁합! 큐티 화이트가 있어요. ' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '사랑이 피어나는 부드러운 생크림 케이크와 함께 즐거운 시간입니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '티라미수|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '깊고 진한 맛의 티라미수 케이크를 좋아하시는군요' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_47' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_47' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '티라미수 오리지날레' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_47.png' }, 'referenceText': { 'type': 'string', 'value': '이탈리아 베네치아에 본연의 맛을 그대로 간직한 티라미수 오리지날레가 있어요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 모카스폰지와 부드러운 마스카포네치즈가 어우러져 있는 깊고 진한 맛의 티라미수 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '20대|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '상큼한 20대에게는 상큼한 맛의 케이크가 딱이겠죠?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_49' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_49' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '러블리화이트케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_49.png' }, 'referenceText': { 'type': 'string', 'value': '바로 러블리화이트케이크가 20대를 위한 케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '고소한 생크림과 상큼한 과일이 어우러진 파리바게뜨 인기 생크림 케이크로 많은 사랑을 받고 있답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '30대|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '30대에게 가장 핫한 케이크를 추천해 드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_50' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_50' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '치즈케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_50.png' }, 'referenceText': { 'type': 'string', 'value': '입안에서 사르르 녹는 치즈케이크가 그 주인공이에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '크림치즈의 부드럽고 촉촉한 맛이 일품으로 오랜 기간 사랑 받아온 최고의 치즈케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '40대|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '40대가 좋아하는 케이크를 찾으시는군요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_51' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_51' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '진한듀얼치즈케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_51.png' }, 'referenceText': { 'type': 'string', 'value': '그렇다면 진한듀얼치즈케이크가 딱이에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '2가지 리얼치즈로 깊고 진한 치즈의 맛을 느낄 수 있는 프리미엄 치즈케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '50대|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '고구마에 달콤한 맛이라면 50대 고객님의 입맛을 사로잡을거에요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_52' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_52' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '고구마가 반한 티라미수' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_52.png' }, 'referenceText': { 'type': 'string', 'value': '그렇다면 고구마가 반한 티라미수 어떨까요?' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '진한 티라미수케이크와 달콤한 밤고구마케이크, 두 가지 맛을 한 번에 맛볼 수 있었요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '할머니|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '할머니에게 케이크 선물을 하시는 걸 보니 효자효녀신가봐요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_53' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_53' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '프리미엄베리생크림' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_53.png' }, 'referenceText': { 'type': 'string', 'value': '할머니를 위해 프리미엄베리생크림을 추천드려요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 화이트 스폰지와 상큼한 베리가 어우러진 고소한 생크림 케이크로 할머니 입맛에 딱 맞을거에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '할아버지|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '할아버지에게 케이크 선물을 하시려나봐요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_54' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_54' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '고구마가 반한 티라미수' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_54.png' }, 'referenceText': { 'type': 'string', 'value': '고구마가 반한 티라미수를 선물드려보세요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '진한 티라미수케이크와 달콤한 밤고구마케이크, 두 가지 맛으로 할아버지 입가에 웃음이 번질거에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '집들이|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '집들이 주인공 입맛을 잘 모르셔도 걱정할 필요가 없어요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_55' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_55' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '사각사각 상콤 바구니' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_55.png' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 생크림과 달콤한 과일의 궁합이 일품인 사각사각 상콤바구니 케이크는 모두가 좋아하시거든요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '생과일이 듬뿍 들어있고,  부드러운 생크림이 녹아 내리는 파리바게뜨 인기 생크림 케이크에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '친구|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '어! 마침 딱 맞는 케이크가 있어요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_56' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_56' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '사각사각 상콤 바구니' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_56.png' }, 'referenceText': { 'type': 'string', 'value': '바로 촉촉한 생크림과 달콤한 과일의 궁합이 일품인 사각사각 상콤바구니 케이크에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '생과일이 듬뿍 들어있고,  부드러운 생크림이 녹아 내리는 인기 생크림케이크로 함께 즐기기에 손색이 없답니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '학생|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '학생들이 먹기에는 부드러우면서 달콤한 케이크가 좋을 것 같아요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_57' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_57' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '초코우유푸딩케이크' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_57.png' }, 'referenceText': { 'type': 'string', 'value': '마침 초코우유푸딩케이크가 있네요~' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '부드러운 초코우유 푸딩 속 바삭한 초코크런치가 들어있는 뛰어난 식감의 떠먹는 케이크로 학생들에게 인기가 짱이에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '선생님|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '선생님께 드릴 케이크를 찾으시는군요?' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_58' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_58' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '티라미수 오리지날레' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_58.png' }, 'referenceText': { 'type': 'string', 'value': '이탈리아 베네치아에 본연의 맛을 그대로 간직한 티라미수 오리지날레라면 선생님께서 좋아하실거에요.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 모카스폰지와 부드러운 마스카포네치즈가 어우러져 있는 깊고 진한 맛의 티라미수 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
,
{ 'slot': '회사|케이크', 'value': { 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '회사에서 동료들과 드시기에 좋은 케이크를 추천해드릴께요.' }, 'referenceUrl': { 'type': 'string', 'value': 'CAKE_59' }, 'thumbImageUrl': { 'type': 'string', 'value': 'CAKE_59' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '티라미수 오리지날레' }, 'imageUrl': { 'type': 'url', 'value': 'CAKE_59.png' }, 'referenceText': { 'type': 'string', 'value': '이탈리아 베네치아에 본연의 맛을 그대로 간직한 티라미수 오리지날레가 그 주인공이에요' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '촉촉한 모카스폰지와 부드러운 마스카포네치즈가 어우러져 있는 깊고 진한 맛의 티라미수 케이크랍니다.' }, 'referenceUrl': { 'type': 'string', 'value': '' }, 'thumbImageUrl': { 'type': 'string', 'value': '' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '숫자초와 모자도 있으니 우리 점원에게 말씀해주시면 바로 준비해드릴께요. 맛있는 하루되세요~' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M12' } } ] } }
];

const emotion_list = [ 
//{ 'id': 'CAKE_01', 'value': [ { 'face': '윙크 표정', 'motion': '끄덕이는 모션' }, { 'face': '윙크 표정', 'motion': '흔들기 모션' }, { 'face': '윙크 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_01', 'value': [ { 'face': '$F4', 'motion': '$M2' }, { 'face': '$F4', 'motion': '$M6' }, { 'face': '$F4', 'motion': '$M9' } ] },
{ 'id': 'CAKE_02', 'value': [ { 'face': '좋아하는 표정', 'motion': '끄덕이는 모션' }, { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' } ] },
//{ 'id': 'CAKE_03', 'value': [ { 'face': '호기심 표정', 'motion': '뽐내는 모션1' }, { 'face': '사랑하는 표정', 'motion': '끄덕이는 모션' }, { 'face': '좋아하는 표정', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_03', 'value': [ { 'face': '$F9', 'motion': '$M1' }, { 'face': '$F3', 'motion': '$M2' }, { 'face': '$F2', 'motion': '$M1' } ] },
{ 'id': 'CAKE_04', 'value': [ { 'face': '윙크 표정', 'motion': '끄덕이는 모션' }, { 'face': '좋아하는 표정', 'motion': '고민하는 모션' }, { 'face': '좋아하는 표정', 'motion': '인사 모션' } ] },
//{ 'id': 'CAKE_05', 'value': [ { 'face': '사랑하는 표정', 'motion': '흔들기 모션' }, { 'face': '좋아하는 표정', 'motion': '흔들기 모션' }, { 'face': '눈 깜박이기', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_05', 'value': [ { 'face': '$F3', 'motion': '$M12' }, { 'face': '$F0', 'motion': '$M12' }, { 'face': '$F0', 'motion': '$M1' } ] },
{ 'id': 'CAKE_06', 'value': [ { 'face': '웃는 표정', 'motion': '뽐내는 모션2' }, { 'face': '웃는 표정', 'motion': '인사 모션' }, { 'face': '눈 깜박이기', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_07', 'value': [ { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' }, { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' }, { 'face': '윙크 표정', 'motion': '고개 숙이기 모션' } ] },
//{ 'id': 'CAKE_08', 'value': [ { 'face': '좋아하는 표정', 'motion': '인사 모션' }, { 'face': '사랑하는 표정', 'motion': '고민하는 모션' }, { 'face': '사랑하는 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_08', 'value': [ { 'face': '$F1', 'motion': '$M1' }, { 'face': '$F3', 'motion': '$M17' }, { 'face': '$F3', 'motion': '$M1' } ] },
{ 'id': 'CAKE_09', 'value': [ { 'face': '사랑하는 표정', 'motion': '뽐내는 모션1' }, { 'face': '웃는 표정', 'motion': '고민하는 모션' }, { 'face': '사랑하는 표정', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_10', 'value': [ { 'face': '눈 깜박이기', 'motion': '뽐내는 모션1' }, { 'face': '좋아하는 표정', 'motion': '뽐내는 모션1' }, { 'face': '호기심 표정', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_11', 'value': [ { 'face': '사랑하는 표정', 'motion': '고민하는 모션' }, { 'face': '사랑하는 표정', 'motion': '뽐내는 모션1' }, { 'face': '좋아하는 표정', 'motion': '끄덕이는 모션' } ] },
{ 'id': 'CAKE_12', 'value': [ { 'face': '좋아하는 표정', 'motion': '고민하는 모션' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션1' }, { 'face': '웃는 표정', 'motion': '인사 모션' } ] },
{ 'id': 'CAKE_13', 'value': [ { 'face': '웃는 표정', 'motion': '고민하는 모션' }, { 'face': '윙크 표정', 'motion': '끄덕이는 모션' }, { 'face': '윙크 표정', 'motion': '인사 모션' } ] },
{ 'id': 'CAKE_14', 'value': [ { 'face': '사랑하는 표정', 'motion': '끄덕이는 모션' }, { 'face': '눈 깜박이기', 'motion': '끄덕이는 모션' }, { 'face': '웃는 표정', 'motion': '고개 숙이기 모션' } ] },
{ 'id': 'CAKE_15', 'value': [ { 'face': '윙크 표정', 'motion': '뽐내는 모션1' }, { 'face': '사랑하는 표정', 'motion': '흔들기 모션' }, { 'face': '사랑하는 표정', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_16', 'value': [ { 'face': '호기심 표정', 'motion': '고개들기 모션' }, { 'face': '호기심 표정', 'motion': '고개들기 모션' }, { 'face': '사랑하는 표정', 'motion': '흔들기 모션' } ] },
//{ 'id': 'CAKE_17', 'value': [ { 'face': '웃는 표정', 'motion': '고개들기 모션' }, { 'face': '웃는 표정', 'motion': '끄덕이는 모션' }, { 'face': '윙크 표정', 'motion': '흔들기 모션' } ] },
{ 'id': 'CAKE_17', 'value': [ { 'face': '$F1', 'motion': '$M3' }, { 'face': '$F1', 'motion': '$M2' }, { 'face': '$F0', 'motion': '$M12' } ] },
{ 'id': 'CAKE_18', 'value': [ { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '윙크 표정', 'motion': '뽐내는 모션1' }, { 'face': '좋아하는 표정', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_19', 'value': [ { 'face': '좋아하는 표정', 'motion': '뽐내는 모션1' }, { 'face': '좋아하는 표정', 'motion': '뽐내는 모션2' }, { 'face': '사랑하는 표정', 'motion': '고민하는 모션' } ] },
{ 'id': 'CAKE_20', 'value': [ { 'face': '윙크 표정', 'motion': '흔들기 모션' }, { 'face': '좋아하는 표정', 'motion': '고개들기 모션' }, { 'face': '윙크 표정', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_21', 'value': [ { 'face': '사랑하는 표정', 'motion': '고개들기 모션' }, { 'face': '눈 깜박이기', 'motion': '뽐내는 모션1' }, { 'face': '윙크 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_22', 'value': [ { 'face': '좋아하는 표정', 'motion': '흔들기 모션' }, { 'face': '윙크 표정', 'motion': '인사 모션' }, { 'face': '호기심 표정', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_23', 'value': [ { 'face': '웃는 표정', 'motion': '끄덕이는 모션' }, { 'face': '좋아하는 표정', 'motion': '끄덕이는 모션' }, { 'face': '좋아하는 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_24', 'value': [ { 'face': '웃는 표정', 'motion': '뽐내는 모션1' }, { 'face': '윙크 표정', 'motion': '흔들기 모션' }, { 'face': '웃는 표정', 'motion': '고민하는 모션' } ] },
{ 'id': 'CAKE_25', 'value': [ { 'face': '호기심 표정', 'motion': '뽐내는 모션2' }, { 'face': '윙크 표정', 'motion': '고개 숙이기 모션' }, { 'face': '웃는 표정', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_26', 'value': [ { 'face': '좋아하는 표정', 'motion': '끄덕이는 모션' }, { 'face': '웃는 표정', 'motion': '흔들기 모션' }, { 'face': '좋아하는 표정', 'motion': '고민하는 모션' } ] },
{ 'id': 'CAKE_27', 'value': [ { 'face': '눈 깜박이기', 'motion': '끄덕이는 모션' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션2' }, { 'face': '사랑하는 표정', 'motion': '끄덕이는 모션' } ] },
{ 'id': 'CAKE_28', 'value': [ { 'face': '웃는 표정', 'motion': '고개 숙이기 모션' }, { 'face': '사랑하는 표정', 'motion': '고개들기 모션' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_29', 'value': [ { 'face': '웃는 표정', 'motion': '인사 모션' }, { 'face': '윙크 표정', 'motion': '고개들기 모션' }, { 'face': '윙크 표정', 'motion': '끄덕이는 모션' } ] },
{ 'id': 'CAKE_30', 'value': [ { 'face': '윙크 표정', 'motion': '인사 모션' }, { 'face': '호기심 표정', 'motion': '뽐내는 모션2' }, { 'face': '호기심 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_31', 'value': [ { 'face': '사랑하는 표정', 'motion': '뽐내는 모션2' }, { 'face': '좋아하는 표정', 'motion': '인사 모션' }, { 'face': '좋아하는 표정', 'motion': '흔들기 모션' } ] },
{ 'id': 'CAKE_32', 'value': [ { 'face': '윙크 표정', 'motion': '고개 숙이기 모션' }, { 'face': '사랑하는 표정', 'motion': '뽐내는 모션2' }, { 'face': '눈 깜박이기', 'motion': '끄덕이는 모션' } ] },
{ 'id': 'CAKE_37', 'value': [ { 'face': '좋아하는 표정', 'motion': '뽐내는 모션2' }, { 'face': '눈 깜박이기', 'motion': '뽐내는 모션2' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_38', 'value': [ { 'face': '좋아하는 표정', 'motion': '고개들기 모션' }, { 'face': '호기심 표정', 'motion': '뽐내는 모션1' }, { 'face': '눈 깜박이기', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_42', 'value': [ { 'face': '눈 깜박이기', 'motion': '뽐내는 모션2' }, { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' } ] },
{ 'id': 'CAKE_43', 'value': [ { 'face': '호기심 표정', 'motion': '뽐내는 모션1' }, { 'face': '사랑하는 표정', 'motion': '끄덕이는 모션' }, { 'face': '좋아하는 표정', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_44', 'value': [ { 'face': '윙크 표정', 'motion': '끄덕이는 모션' }, { 'face': '좋아하는 표정', 'motion': '고민하는 모션' }, { 'face': '좋아하는 표정', 'motion': '인사 모션' } ] },
{ 'id': 'CAKE_45', 'value': [ { 'face': '사랑하는 표정', 'motion': '흔들기 모션' }, { 'face': '좋아하는 표정', 'motion': '흔들기 모션' }, { 'face': '눈 깜박이기', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_46', 'value': [ { 'face': '웃는 표정', 'motion': '뽐내는 모션2' }, { 'face': '웃는 표정', 'motion': '인사 모션' }, { 'face': '눈 깜박이기', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_47', 'value': [ { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' }, { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' }, { 'face': '윙크 표정', 'motion': '고개 숙이기 모션' } ] },
{ 'id': 'CAKE_49', 'value': [ { 'face': '웃는 표정', 'motion': '뽐내는 모션2' }, { 'face': '호기심', 'motion': '뽐내는 모션2' }, { 'face': '사랑하는 표정', 'motion': '흔들기 모션' } ] },
{ 'id': 'CAKE_50', 'value': [ { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '웃는 표정', 'motion': '고개들기 모션' }, { 'face': '좋아하는 표정', 'motion': '인사 모션' } ] },
{ 'id': 'CAKE_51', 'value': [ { 'face': '웃는 표정', 'motion': '뽐내는 모션1' }, { 'face': '호기심', 'motion': '뽐내는 모션1' }, { 'face': '사랑하는 표정', 'motion': '고민하는 모션' } ] },
{ 'id': 'CAKE_52', 'value': [ { 'face': '눈 깜박이기', 'motion': '뽐내는 모션2' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션2' }, { 'face': '좋아하는 표정', 'motion': '고민하는 모션' } ] },
{ 'id': 'CAKE_53', 'value': [ { 'face': '웃는 표정', 'motion': '고민하는 모션' }, { 'face': '호기심', 'motion': '뽐내는 모션2' }, { 'face': '사랑하는 표정', 'motion': '뽐내는 모션2' } ] },
{ 'id': 'CAKE_54', 'value': [ { 'face': '웃는 표정', 'motion': '뽐내는 모션1' }, { 'face': '호기심', 'motion': '고개들기 모션' }, { 'face': '사랑하는 표정', 'motion': '고개들기 모션' } ] },
{ 'id': 'CAKE_55', 'value': [ { 'face': '눈 깜박이기', 'motion': '뽐내는 모션1' }, { 'face': '웃는 표정', 'motion': '흔들기 모션' }, { 'face': '좋아하는 표정', 'motion': '고민하는 모션' } ] },
{ 'id': 'CAKE_56', 'value': [ { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션1' }, { 'face': '좋아하는 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_57', 'value': [ { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '웃는 표정', 'motion': '뽐내는 모션2' }, { 'face': '좋아하는 표정', 'motion': '고개 숙이기 모션' } ] },
{ 'id': 'CAKE_58', 'value': [ { 'face': '웃는 표정', 'motion': '끄덕이는 모션' }, { 'face': '호기심', 'motion': '고개들기 모션' }, { 'face': '사랑하는 표정', 'motion': '뽐내는 모션1' } ] },
{ 'id': 'CAKE_59', 'value': [ { 'face': '눈 깜박이기', 'motion': '고개들기 모션' }, { 'face': '웃는 표정', 'motion': '고개들기 모션' }, { 'face': '좋아하는 표정', 'motion': '고개들기 모션' } ] }
];

const response_template = '{"outputSpeech": {"type":"SimpleSpeech"}, "card": {}, "directives": [], "shouldEndSession": false}';

const error_response_list = [
{ 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '힝~~~죄송해요~ 빠리바게뜨에서 일한지 얼마 안되어서요.' }, 'referenceUrl': { 'type': 'string', 'value': '$F5' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M16' } }, { 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '다시 한 번만 말씀해주시겠어요? 옆에 안내문을 참고해주세요.' }, 'referenceUrl': { 'type': 'string', 'value': '$F1' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M5' } } ] }, 
{ 'type': 'ImageList', 'thumbImageUrlList': [{ 'imageReference': { 'type': 'string', 'value': '' },  'imageTitle': { 'type': 'string', 'value': '' }, 'imageUrl': { 'type': 'url', 'value': '' }, 'referenceText': { 'type': 'string', 'value': '아직 많이 부족한 저를 위해 다시 한 번만 말씀해주시겠어요? 옆에 안내문을 참고해주세요.' }, 'referenceUrl': { 'type': 'string', 'value': '$F10' }, 'thumbImageUrl': { 'type': 'string', 'value': '$M16' } } ] }
];

module.exports = {
	RESPONSE_LIST : response_list,
	EMOTION_LIST : emotion_list,
	RESPONSE_TEMPLATE : response_template,
	ERROR_RESPONSE_LIST : error_response_list
};